### ISSUE TITLE
Plugin installer failing

### ISSUE THREAD

**Issue by mentiondev** [ssplugin/ss-craft-membership#1]
Craft CMS plugin installer failing.

I can't find the project on [packagist](https://packagist.org/). So I think that's why it can't be installed via composer yet.

**Comment by ssplugin** [comment]
@mentiondev yes. You are right. We have not added our plugin on packagist because this plugin is only for craft cms. That's why you need to install the plugin from the Craft CMS Plugin Store.
Go to the Craft CMS dashboard **Plugin store** and Find out **SS Membership** and Install from there. This is the only way to install our plugin.

**Comment by mentiondev** [comment]
Craft 3 requires composer

So installing in from the plugin store doesn't work as it's not setup for composer, it just prints a fatal error message. So it can't be installed currently from the plugin store or via composer.

i.e when you install directly from Craft it adds `"ssplugin/ss-membership": "1.0.0",` to the composer.json file

And need to be able to run `composer require ssplugin/ss-membership` in the terminal for it to work with `composer install`

**Comment by ssplugin** [comment]
@mentiondev 

We have added a plugin on packagist also. Now you can able to download plugins from the composer.
